-- ==========================================================
-- FULL SKILL COURSES UPDATE FROM PDF (INSERT ONLY)
-- Source: Skill Development Courses Certificates (5) (3) (5).pdf
-- Generated automatically on 2026-03-06
-- ==========================================================

insert into education_modes(name)
values ('Skill Certification')
on conflict (name) do nothing;

insert into universities (name, slug, location, mode_supported, logo, description)
values
('Glocal University', 'glocal-university', 'Saharanpur, India', array['Vocational','Skill Certification'], '/logos/universities/glocal-university.jpeg', 'Skill certification and vocational programs.')
on conflict (slug) do nothing;

with domains(name, slug) as (
  values
    ('Agriculture', 'agriculture'),
    ('Automobile', 'automobile'),
    ('Child Education', 'child-education'),
    ('Civil Construction', 'civil-construction'),
    ('Soft Skills', 'soft-skills'),
    ('Dairy Education', 'dairy-education'),
    ('Electrical and Electronics', 'electrical-and-electronics'),
    ('Fisheries', 'fisheries'),
    ('Home Maintenance', 'home-maintenance'),
    ('Cottage Industry', 'cottage-industry'),
    ('Interior and Exterior Design', 'interior-and-exterior-design'),
    ('Office Management', 'office-management'),
    ('Poultry', 'poultry'),
    ('Acupuncture', 'acupuncture'),
    ('Ayurveda', 'ayurveda'),
    ('Beauty and Wellness', 'beauty-and-wellness'),
    ('Computing and Information Technology', 'computing-and-information-technology'),
    ('Fire and Safety', 'fire-and-safety'),
    ('Forest and Environmental', 'forest-and-environmental'),
    ('Gems and Jewellery', 'gems-and-jewellery'),
    ('Geo Information Systems', 'geo-information-systems'),
    ('Hotel Management and Tourism', 'hotel-management-and-tourism'),
    ('Language Studies', 'language-studies'),
    ('Creative Industry', 'creative-industry'),
    ('Siddha Medicine', 'siddha-medicine'),
    ('Sports', 'sports'),
    ('Technical Training', 'technical-training'),
    ('Textile Technology', 'textile-technology'),
    ('Unani Medicine', 'unani-medicine'),
    ('Yoga and Naturopathy', 'yoga-and-naturopathy'),
    ('Management', 'management'),
    ('Aviation', 'aviation'),
    ('Banking and Finance', 'banking-and-finance'),
    ('Fashion Design', 'fashion-design'),
    ('Media and Film', 'media-and-film'),
    ('Logistics and Transportation', 'logistics-and-transportation'),
    ('Marine Technology', 'marine-technology'),
    ('Solar Technology', 'solar-technology'),
    ('Mental Health', 'mental-health'),
    ('Marketing', 'marketing')
)
insert into course_sectors(name, slug)
select name, slug from domains
on conflict (slug) do nothing;

with base_courses(sector_name, topic) as (
  values
    ('Agriculture', 'Agriculture And Allied Technology'),
    ('Agriculture', 'Horticulture'),
    ('Agriculture', 'Cold Storage Technology'),
    ('Agriculture', 'Bee Keeping Equipment Manufacturing Techniques'),
    ('Agriculture', 'Farm Equipment Mechanic'),
    ('Agriculture', 'Plant Protection'),
    ('Agriculture', 'Tractor And Power Tiller Mechanic'),
    ('Agriculture', 'Medicinal Plants Processing'),
    ('Agriculture', 'Coconut- By Products Processing Technician'),
    ('Agriculture', 'Horticulture Salesman'),
    ('Agriculture', 'Preservation Technician (horticultural)'),
    ('Agriculture', 'Laboratory Technician (horticultural)'),
    ('Agriculture', 'Floriculture Technician'),
    ('Agriculture', 'Flowers And Plants Packaging Technician'),
    ('Agriculture', 'Land Spacing Technician'),
    ('Agriculture', 'Florist Salesman'),
    ('Agriculture', 'Agriculture Supervisor'),
    ('Agriculture', 'Agriculture Science'),
    ('Agriculture', 'Plant Protection Technician'),
    ('Agriculture', 'Vocational Instructor (crop Production)'),
    ('Agriculture', 'Agro-based Industrial Management'),
    ('Agriculture', 'Plant Nursery Making'),
    ('Agriculture', 'Water Shed Protection And Management'),
    ('Agriculture', 'Fodder Crops Cultivation'),
    ('Agriculture', 'Crops Production'),
    ('Agriculture', 'Mushroom Cultivation And Protection'),
    ('Agriculture', 'Honey Bee Keeping Technician'),
    ('Agriculture', 'Rain Water Harvesting Technician'),
    ('Agriculture', 'Soil Conservation Technician'),
    ('Agriculture', 'Vermiculture Technician'),
    ('Agriculture', 'Irrigation Equipment Mechanic'),
    ('Agriculture', 'Vanilla Cultivation Plant Protection'),
    ('Agriculture', 'Medicinal Plant Cultivation Technology'),
    ('Agriculture', 'Honey Processing Technician'),
    ('Agriculture', 'Azzola Cultivation Technician'),
    ('Agriculture', 'Food Preservation Technology'),
    ('Agriculture', 'Seed Production Technician'),
    ('Agriculture', 'Food Technology'),
    ('Agriculture', 'Apiary Technician'),
    ('Agriculture', 'Certificate In Agriculture Science'),
    ('Agriculture', 'Agriculture Crop Production'),
    ('Agriculture', 'Plant Protection And Pesticides Management'),
    ('Agriculture', 'Horticulture Supervisor Training'),
    ('Automobile', 'Automobile Technology'),
    ('Automobile', 'Heavy Motor Vehicle Mechanism'),
    ('Automobile', 'Four Wheeler Mechanic (lmv)'),
    ('Automobile', 'Automobile Electronics Technology'),
    ('Automobile', 'Car A/c Mechanic'),
    ('Automobile', 'Spray Painter'),
    ('Automobile', 'Plant Maintenance Technician'),
    ('Automobile', 'Junior Plant Operator'),
    ('Automobile', 'Two Wheeler Mechanic'),
    ('Automobile', 'Backhoe Loader Operation & Maintenance'),
    ('Automobile', 'Diesel Fuel System Service Mechanic'),
    ('Automobile', 'Crane Operation & Maintenance'),
    ('Automobile', 'Fork Lift Operation & Maintenance'),
    ('Automobile', 'Inspector Of Auto Manufacturing Industry'),
    ('Automobile', 'Hydraulic Excavator Operation & Maintenance'),
    ('Automobile', 'Diesel Engine Technology'),
    ('Automobile', 'Vehicle Surveyor'),
    ('Automobile', 'Automobile Engineering'),
    ('Automobile', 'Heavy Crane Operation & Management'),
    ('Automobile', 'Petrol Engine Technology'),
    ('Automobile', 'Gas Welder'),
    ('Automobile', 'Light Motor Vehicle Mechanism'),
    ('Automobile', 'Diesel Mechanism (stationery & Mobile Engines)'),
    ('Automobile', 'Fork Lift Driving Cum Maintenance'),
    ('Automobile', 'Sheet Metal Works & Tinkering'),
    ('Automobile', 'Automobile Engineering Techniques'),
    ('Automobile', 'Four Wheeler Mechanism'),
    ('Automobile', 'Operation & Maintenance Of Hydraulic Heavy Machineries'),
    ('Automobile', 'Operation & Maintenance Of Heavy Machineries (back Hoe Loader)'),
    ('Automobile', 'Operation & Maintenance Of Heavy Machineries (hydraulic Excavator)'),
    ('Automobile', 'Operation & Maintenance Of Heavy Machineries (crane)'),
    ('Automobile', 'Operation & Maintenance Of Heavy Machineries (fork Lift)'),
    ('Automobile', 'Automobile Engineering Technology'),
    ('Automobile', 'Mechanical Fitter Cum CNC Machine Operator'),
    ('Automobile', 'Hydraulic Mechanical Engineering'),
    ('Child Education', 'Pre-primary Education'),
    ('Child Education', 'Nursery Teacher Training'),
    ('Child Education', 'Montessori And Child Education'),
    ('Child Education', 'Creche And Pre-school Management'),
    ('Child Education', 'Anganwadi Worker'),
    ('Child Education', 'Anganwadi Supervisor'),
    ('Child Education', 'Early Childhood Care And Education'),
    ('Child Education', 'Child Remedial Education'),
    ('Child Education', 'Art And Craft'),
    ('Child Education', 'Pre-school Education (dpse)'),
    ('Child Education', 'Technology In Teaching (cptt)'),
    ('Child Education', 'Classroom Teaching Instructional Strategies'),
    ('Child Education', 'Communication Skills And English Language'),
    ('Child Education', 'Elementary Education,advanced'),
    ('Child Education', 'Nursery And Primary Education'),
    ('Child Education', 'Montessori And Grade Level Education'),
    ('Child Education', 'Virtual Teaching'),
    ('Civil Construction', 'Architectural Technology'),
    ('Civil Construction', 'Civil Construction Supervisor'),
    ('Civil Construction', 'Civil Draughts Man'),
    ('Civil Construction', 'Building Supervisor'),
    ('Civil Construction', 'Land Survey Assistant'),
    ('Civil Construction', 'Building Design'),
    ('Civil Construction', 'Land Survey & Documentation'),
    ('Civil Construction', 'Civil Engineering Techniques'),
    ('Civil Construction', 'Structural Technician'),
    ('Civil Construction', 'Building Quality Management'),
    ('Civil Construction', 'Land Survey'),
    ('Civil Construction', 'Land Surveying (using Total Station & GPS)'),
    ('Civil Construction', 'Quantity Surveying & Billing Engineer In Civil Construction'),
    ('Civil Construction', 'Construction Management'),
    ('Soft Skills', 'Spoken English'),
    ('Soft Skills', 'Personality Development'),
    ('Soft Skills', 'Communication Skills Development'),
    ('Soft Skills', 'Entrepreneurship Skills Development'),
    ('Soft Skills', 'Personality Trainer'),
    ('Soft Skills', 'Communication Skills Trainer'),
    ('Soft Skills', 'Entrepreneurship Trainer'),
    ('Soft Skills', 'Employability Skills'),
    ('Dairy Education', 'Dairy Technology'),
    ('Dairy Education', 'Dairy Products Processing'),
    ('Dairy Education', 'Dairy Dock Technician'),
    ('Dairy Education', 'Milk Chilling Centre Technician'),
    ('Dairy Education', 'Dairy Laboratory Technician'),
    ('Dairy Education', 'Dairy Technician'),
    ('Dairy Education', 'Dairy Store Technician'),
    ('Electrical and Electronics', 'Electrical & Electronics Technology'),
    ('Electrical and Electronics', 'Electronics & Communication Technology'),
    ('Electrical and Electronics', 'Mobile Phone Technician'),
    ('Electrical and Electronics', 'Radio And Television Service'),
    ('Electrical and Electronics', 'Domestic Electrical Motor Winder'),
    ('Electrical and Electronics', 'Industrial Electronics Technology'),
    ('Electrical and Electronics', 'Power Invertor Technician'),
    ('Electrical and Electronics', 'Consumer Electronics Maintenance'),
    ('Electrical and Electronics', 'Electrician'),
    ('Electrical and Electronics', 'Heavy Electrical Motor Winder'),
    ('Electrical and Electronics', 'Air Conditioning And Refrigeration'),
    ('Electrical and Electronics', 'Mobile Phone Technology'),
    ('Electrical and Electronics', 'Clock & Watch Repair Technician'),
    ('Electrical and Electronics', 'Telephone Technician'),
    ('Electrical and Electronics', 'Gas Stove Technician'),
    ('Electrical and Electronics', 'Emergency Light Technician'),
    ('Electrical and Electronics', 'Sewing Machine Technician'),
    ('Electrical and Electronics', 'Radio & TV Assembler'),
    ('Electrical and Electronics', 'Domestic Electronic Equipment Servicing'),
    ('Electrical and Electronics', 'Cable TV Network Technician'),
    ('Electrical and Electronics', 'Stabilizer Maker'),
    ('Electrical and Electronics', 'Invertor, Ups Technology'),
    ('Electrical and Electronics', 'Cable TV Operator'),
    ('Electrical and Electronics', 'DTH Technology'),
    ('Electrical and Electronics', 'Electronic Chock Maker'),
    ('Electrical and Electronics', 'Electronics Technician'),
    ('Electrical and Electronics', 'Embedded System & PLC Technician'),
    ('Electrical and Electronics', 'Electrical Power Drives Technician'),
    ('Electrical and Electronics', 'Electrical Motor Rewinding'),
    ('Electrical and Electronics', 'Industrial Electronics'),
    ('Electrical and Electronics', 'TV Mechanism'),
    ('Electrical and Electronics', 'H.v.a.c. Technician'),
    ('Electrical and Electronics', 'Generator Operation & Service Technology'),
    ('Electrical and Electronics', 'Air Conditioning & Refrigeration Mechanism'),
    ('Electrical and Electronics', 'Refrigeration & Air Conditioning Engineering'),
    ('Electrical and Electronics', 'Cctv Technology & Surveillance'),
    ('Electrical and Electronics', 'Cctv Technician'),
    ('Electrical and Electronics', 'Heat Ventilation & Air Condition Engineering'),
    ('Electrical and Electronics', 'Refrigeration,heat Ventilation & Air Condition Engg'),
    ('Electrical and Electronics', 'Pdm-ultrasound'),
    ('Electrical and Electronics', 'Predictive Maintenance'),
    ('Electrical and Electronics', 'Electrical Qc'),
    ('Electrical and Electronics', 'Pdm-infrared Thermography'),
    ('Electrical and Electronics', 'Pdm-vibration Analysis'),
    ('Electrical and Electronics', 'Concrete Ndt'),
    ('Fisheries', 'Fisheries Technology'),
    ('Fisheries', 'Fisheries Laboratory Technician'),
    ('Fisheries', 'Fisheries Seed Production Technician'),
    ('Fisheries', 'Fisheries Feed Technician'),
    ('Fisheries', 'Hatchery Operator'),
    ('Fisheries', 'Net And Gear Technician'),
    ('Fisheries', 'Fisheries Field Technician'),
    ('Fisheries', 'Fisheries Survey Technician'),
    ('Fisheries', 'Cold Storage Technology'),
    ('Fisheries', 'Fish Farmer'),
    ('Fisheries', 'Fish Bank Techniques'),
    ('Fisheries', 'Pituitary Bank Techniques'),
    ('Fisheries', 'Ornamental Fish Cultivation And Management'),
    ('Fisheries', 'Boat Construction Technology'),
    ('Fisheries', 'Skilled Frp Worker'),
    ('Fisheries', 'Spawn Producing Techniques'),
    ('Fisheries', 'Fisheries Feed Manufacturing Techniques'),
    ('Home Maintenance', 'Home Science'),
    ('Home Maintenance', 'Home Maintenance Technician'),
    ('Home Maintenance', 'Domestic House Keeping'),
    ('Home Maintenance', 'Domestic Helper'),
    ('Home Maintenance', 'Home Network Management'),
    ('Home Maintenance', 'Home Network Assistant'),
    ('Home Maintenance', 'Home Management (multiskilling And Residential)'),
    ('Home Maintenance', 'Home Management And Geriatric Care, Residential'),
    ('Home Maintenance', 'Steam Pressing Technician'),
    ('Home Maintenance', 'Wet Cleaning Technician'),
    ('Home Maintenance', 'Laundry & Wet Cleaning Technician'),
    ('Home Maintenance', 'Home Management And Geriatric Care'),
    ('Cottage Industry', 'Book Binding'),
    ('Cottage Industry', 'Terracotta Work'),
    ('Cottage Industry', 'Wire Bag Knitting'),
    ('Cottage Industry', 'Fancy Articles Making'),
    ('Cottage Industry', 'Soft Toys Making'),
    ('Cottage Industry', 'Doll Making'),
    ('Cottage Industry', 'Aluminum Foil Work'),
    ('Cottage Industry', 'Jute Work/craft'),
    ('Cottage Industry', 'Canopy Work'),
    ('Cottage Industry', 'Cloth Bag Making'),
    ('Cottage Industry', 'Toys (plaster Of Paris)'),
    ('Cottage Industry', 'Coir Items Making'),
    ('Cottage Industry', 'Mat Making'),
    ('Cottage Industry', 'Umbrella Assembling'),
    ('Cottage Industry', 'Paper Covers Making'),
    ('Cottage Industry', 'Wax Decorative Articles Making'),
    ('Cottage Industry', 'Greetings Card Making'),
    ('Cottage Industry', 'Improved Chula Making'),
    ('Cottage Industry', 'File And Envelope Making'),
    ('Cottage Industry', 'Chalk Pieces And Candle Making'),
    ('Cottage Industry', 'Hair Band Making'),
    ('Cottage Industry', 'Rubber Stamps Making'),
    ('Cottage Industry', 'Dry Cleaning'),
    ('Cottage Industry', 'Camphor Making'),
    ('Cottage Industry', 'Perfume Making'),
    ('Cottage Industry', 'Manufacturing Of Jute Bags, Door Mats, Table Mats'),
    ('Cottage Industry', 'Rexin Bag Making'),
    ('Cottage Industry', 'Leather Work'),
    ('Cottage Industry', 'Bamboo Crafts Artisans'),
    ('Interior and Exterior Design', 'Interior Designing'),
    ('Interior and Exterior Design', 'Exterior Designing'),
    ('Interior and Exterior Design', 'Interior & Exterior Designing'),
    ('Interior and Exterior Design', 'Exhibition Designer'),
    ('Interior and Exterior Design', 'Indoor Technician'),
    ('Interior and Exterior Design', 'Design Painter'),
    ('Interior and Exterior Design', 'Sign Board Writer'),
    ('Interior and Exterior Design', 'Thermocol Decorator'),
    ('Interior and Exterior Design', 'Sheet Metal Fabricator'),
    ('Interior and Exterior Design', 'Pot Painting'),
    ('Interior and Exterior Design', 'Oil Painting'),
    ('Interior and Exterior Design', 'Glass Painting'),
    ('Interior and Exterior Design', 'Ceramic Painting'),
    ('Interior and Exterior Design', 'Drawing And Water Colour Painting'),
    ('Interior and Exterior Design', 'Block Painting'),
    ('Interior and Exterior Design', 'Sheet Metal Fabrication'),
    ('Interior and Exterior Design', 'Aluminum Fabrication'),
    ('Interior and Exterior Design', 'Floriculture & Landscaping Technology'),
    ('Interior and Exterior Design', 'Garden Science'),
    ('Interior and Exterior Design', 'Garden Supervisor'),
    ('Interior and Exterior Design', 'Landscaping Technician'),
    ('Interior and Exterior Design', 'Interior Decoration & Designing'),
    ('Interior and Exterior Design', 'Interior And Exterior Architecture'),
    ('Interior and Exterior Design', 'Interior Architecture'),
    ('Interior and Exterior Design', 'Interior And Exterior Architectural Designing'),
    ('Interior and Exterior Design', 'Gardener (mali)'),
    ('Interior and Exterior Design', 'Interior Design And Visualization'),
    ('Office Management', 'Office Practice Management'),
    ('Office Management', 'Secretarial Practice'),
    ('Office Management', 'Personal Secretaryship'),
    ('Office Management', 'Office Assistantship'),
    ('Office Management', 'Basic Financial Services'),
    ('Office Management', 'Purchasing & Store Keeping Technician'),
    ('Office Management', 'Receptionist'),
    ('Office Management', 'Public Relations Officer'),
    ('Office Management', 'Cashier'),
    ('Office Management', 'Office Computer Operator'),
    ('Office Management', 'Electronic Office'),
    ('Office Management', 'Clerical Job In Computerised Office'),
    ('Office Management', 'Computer In Retail Shop'),
    ('Office Management', 'Ledger Clerk'),
    ('Office Management', 'Senior Secondary Level Typewriting English'),
    ('Office Management', 'Stenography'),
    ('Poultry', 'Poultry Technology'),
    ('Poultry', 'Poultry Pharmaceutical Salesmanship'),
    ('Poultry', 'Poultry Health Inspector'),
    ('Poultry', 'Hatchery Technician'),
    ('Poultry', 'Chick Sexer'),
    ('Poultry', 'Poultry Feed Manufacturing Techniques'),
    ('Poultry', 'Poultry Feed Technician'),
    ('Poultry', 'Poultry Laboratory Technician'),
    ('Poultry', 'Poultry Product Technician'),
    ('Poultry', 'Poultry Farm Supervisor'),
    ('Poultry', 'Poultry Farm Record Keeper'),
    ('Poultry', 'Poultry Farmer'),
    ('Poultry', 'Poultry Equipment Manufacturing Techniques'),
    ('Poultry', 'Poultry Management'),
    ('Acupuncture', 'Acupuncture'),
    ('Acupuncture', 'Acupuncture First-aid'),
    ('Acupuncture', 'Acupuncture & Traditional Pulse Diagnosing'),
    ('Acupuncture', 'Cosmetology And Beauty Parlour Management'),
    ('Acupuncture', 'Beauty Technician'),
    ('Acupuncture', 'Acupuncture & Psychology'),
    ('Acupuncture', 'Sujok Acupuncture'),
    ('Acupuncture', 'Aromatherapy And Cosmetic Acupuncture'),
    ('Acupuncture', 'Acupuncture Therapy'),
    ('Acupuncture', 'Magneto Therapy And Acupressure'),
    ('Acupuncture', 'Reflexology And Acupressure'),
    ('Acupuncture', 'Shiatszu Massage And Aromatherapy'),
    ('Acupuncture', 'Iridology And Acupressure'),
    ('Acupuncture', 'Fengshui And Acupuncture'),
    ('Acupuncture', 'Scalp Acupuncture'),
    ('Acupuncture', 'Stress Management By Acupuncture'),
    ('Acupuncture', 'De-addiction By Acupuncture'),
    ('Acupuncture', 'Holography And Acupuncture'),
    ('Acupuncture', 'Acupuncture Management'),
    ('Acupuncture', 'Acupuncture & Healing Techniques'),
    ('Acupuncture', 'Varmaniam Massage Therapy'),
    ('Acupuncture', 'Acupuncture & Varma'),
    ('Acupuncture', 'Integrative Alternative Therapy'),
    ('Acupuncture', 'Traditional Acupuncture & Sujok Acupuncture'),
    ('Acupuncture', 'Acupuncture & Yoga'),
    ('Acupuncture', 'Classical Acupuncture'),
    ('Acupuncture', 'Acupressure'),
    ('Acupuncture', 'Homeopuncture'),
    ('Acupuncture', 'Guasa Therapy & Art Of Foot Neurological Therapy'),
    ('Acupuncture', 'Reflexology And Acu Touch'),
    ('Acupuncture', 'Acupuncture & Physiotherapy'),
    ('Acupuncture', 'Acupuncture & Acupressure'),
    ('Acupuncture', 'Acupuncture And Naturopathy'),
    ('Acupuncture', 'Tibb Acupuncture'),
    ('Acupuncture', 'Acupuncture & Tissue Remedy'),
    ('Acupuncture', 'Acupuncture & Flower Remedy'),
    ('Ayurveda', 'Physiotherapy & Ayurveda'),
    ('Ayurveda', 'Panchakarma & Massage Therapy'),
    ('Ayurveda', 'Ayurveda Patient Care'),
    ('Ayurveda', 'Ayurvedic Beauty Care'),
    ('Ayurveda', 'Ayurveda Massage & Panchakarma Therapy'),
    ('Ayurveda', 'Ayurveda, Panchakarma & Yoga'),
    ('Ayurveda', 'Diabetic Care & Diet By Ayurveda'),
    ('Ayurveda', 'Arthritic Care & Diet By Ayurveda'),
    ('Ayurveda', 'Obesity Care By Ayurveda'),
    ('Ayurveda', 'Spa Massage By Ayurveda'),
    ('Ayurveda', 'Ayurveda Massage & Treatment'),
    ('Ayurveda', 'Ayurveda Patient Care & Panchakarma Therapy'),
    ('Ayurveda', 'Ayurveda Patient Care & Pharmacy'),
    ('Ayurveda', 'Ayurveda, Panchakarma & Patient Care'),
    ('Ayurveda', 'Panchakarma'),
    ('Ayurveda', 'Kalariuzhichil'),
    ('Ayurveda', 'Maseur & Panchakarma'),
    ('Ayurveda', 'Masseura'),
    ('Ayurveda', 'Ayurveda Patient Care Assistant'),
    ('Ayurveda', 'Ayurvedha Pharmacy Assistant'),
    ('Ayurveda', 'Varma & Massage Science'),
    ('Ayurveda', 'Ayurveda And Panchakarma'),
    ('Ayurveda', 'Ayurvedic Gynecology & Obstetrics'),
    ('Ayurveda', 'Ayurvedic Child Health'),
    ('Ayurveda', 'Ayurvedic Cosmetology'),
    ('Ayurveda', 'Wellness Therapy And Management'),
    ('Ayurveda', 'Ayurveda Ksharsutra'),
    ('Ayurveda', 'Beauty And Spa Therapies'),
    ('Ayurveda', 'Ayurvedic Herbal Preparations'),
    ('Ayurveda', 'Holistic Spa Therapies'),
    ('Ayurveda', 'Integrated Spa Therapies'),
    ('Ayurveda', 'Spa Management'),
    ('Ayurveda', 'Ayurvedic Food Science And Cooking'),
    ('Ayurveda', 'Ayurvedic Lifestyle Coach'),
    ('Ayurveda', 'Thai Massage And Treatments'),
    ('Ayurveda', 'Ayurved And Panchagavya Therapy'),
    ('Beauty and Wellness', 'Cosmetology And Beauty Parlour Management'),
    ('Beauty and Wellness', 'Beauty Technician'),
    ('Beauty and Wellness', 'Nature Cure Beauty'),
    ('Beauty and Wellness', 'Self Grooming & Bridal Make Up'),
    ('Beauty and Wellness', 'Henna Making'),
    ('Beauty and Wellness', 'Mehandi Application'),
    ('Beauty and Wellness', 'Bouquet Making & Flower Decoration'),
    ('Beauty and Wellness', 'Cosmetology & Beauty Parlour Management'),
    ('Beauty and Wellness', 'Spa & Beauty'),
    ('Beauty and Wellness', 'Nail Technology'),
    ('Beauty and Wellness', 'Hair Styling'),
    ('Beauty and Wellness', 'Hair Dressing'),
    ('Beauty and Wellness', 'Anti Aging, Facial Aesthetics And Cosmetology'),
    ('Beauty and Wellness', 'Cosmetology And Aesthetics'),
    ('Beauty and Wellness', 'Semi-permanent Makeup & Cosmetic Micropigmentation'),
    ('Computing and Information Technology', 'Computer Hardware Maintenance'),
    ('Computing and Information Technology', 'Computer Applications'),
    ('Computing and Information Technology', 'Software Applications'),
    ('Computing and Information Technology', 'Computer Hardware Maintenance And Network Engineering'),
    ('Computing and Information Technology', 'Computer Science'),
    ('Computing and Information Technology', 'Multimedia'),
    ('Computing and Information Technology', 'Web Designing'),
    ('Computing and Information Technology', 'Mobile Phone Technologycourse'),
    ('Computing and Information Technology', 'Multimedia Animation'),
    ('Computing and Information Technology', 'Data Entry Operator'),
    ('Computing and Information Technology', 'Computer Hardware And Networking'),
    ('Computing and Information Technology', 'Certificate In Oracle'),
    ('Computing and Information Technology', 'Visual C++'),
    ('Computing and Information Technology', 'Asp.net'),
    ('Computing and Information Technology', 'Net'),
    ('Computing and Information Technology', 'Vb.net'),
    ('Computing and Information Technology', 'Cad/cam Programming'),
    ('Computing and Information Technology', 'Global Hardware And Networking'),
    ('Computing and Information Technology', 'Information Technology'),
    ('Computing and Information Technology', 'Preparatory Course In Ceo'),
    ('Computing and Information Technology', 'Auto Cad'),
    ('Computing and Information Technology', 'Preparatory Course In Dtp'),
    ('Computing and Information Technology', 'Java Programming'),
    ('Computing and Information Technology', 'Electronic Office'),
    ('Computing and Information Technology', 'Desktop Publishing'),
    ('Computing and Information Technology', 'C++'),
    ('Computing and Information Technology', 'Clerical Jobs In Computerised Office'),
    ('Computing and Information Technology', 'Operations Of Computer In Retail Shops'),
    ('Computing and Information Technology', 'In Data Entry And Console Operation'),
    ('Computing and Information Technology', 'C Programming'),
    ('Computing and Information Technology', 'Visual Basic'),
    ('Computing and Information Technology', 'Ms-office'),
    ('Computing and Information Technology', 'Open Office'),
    ('Computing and Information Technology', 'Adobe Photoshop'),
    ('Computing and Information Technology', 'Financial Management Software'),
    ('Computing and Information Technology', 'Adobe Page Maker'),
    ('Computing and Information Technology', 'Corel Draw'),
    ('Computing and Information Technology', 'Excel'),
    ('Computing and Information Technology', 'Windows/linux'),
    ('Computing and Information Technology', 'Cobol Programming'),
    ('Computing and Information Technology', 'Internet Applications'),
    ('Computing and Information Technology', 'Computer Faculty Training'),
    ('Computing and Information Technology', 'Computer Tc'),
    ('Computing and Information Technology', 'Computer Application'),
    ('Computing and Information Technology', 'Multimedia Programming'),
    ('Computing and Information Technology', 'Laptop Hardware & Wifi Technology'),
    ('Computing and Information Technology', 'Tally Erp 9'),
    ('Computing and Information Technology', 'Computer Hardware & Networking'),
    ('Computing and Information Technology', 'Doa (ms -office Only)'),
    ('Computing and Information Technology', 'Graphics'),
    ('Computing and Information Technology', '3d Animation'),
    ('Computing and Information Technology', 'J2ee'),
    ('Computing and Information Technology', 'Autocad'),
    ('Computing and Information Technology', 'Sap'),
    ('Computing and Information Technology', 'Software Testing'),
    ('Computing and Information Technology', 'Embedded System'),
    ('Computing and Information Technology', 'Chip Level System'),
    ('Computing and Information Technology', 'Computer Technology'),
    ('Computing and Information Technology', 'Computer Python Programming'),
    ('Computing and Information Technology', 'Animation'),
    ('Computing and Information Technology', 'Digital Marketing'),
    ('Computing and Information Technology', 'Animation Design And Technology'),
    ('Computing and Information Technology', 'Visual Design & Communication'),
    ('Computing and Information Technology', 'Game Design'),
    ('Computing and Information Technology', 'Data Science'),
    ('Computing and Information Technology', '3d Printing Technology'),
    ('Computing and Information Technology', 'User Interface And User Experience (ui/ux)'),
    ('Computing and Information Technology', 'Visual Effects'),
    ('Computing and Information Technology', 'Graphic Web Designing & Development'),
    ('Fire and Safety', 'Fire & Safety Methods'),
    ('Fire and Safety', 'Industrial Safety'),
    ('Fire and Safety', 'Fire Technician'),
    ('Fire and Safety', 'Electrical Safety'),
    ('Fire and Safety', 'Off Shore Safety'),
    ('Fire and Safety', 'Fire Fighting'),
    ('Fire and Safety', 'Construction Safety'),
    ('Fire and Safety', 'Environmental Safety'),
    ('Fire and Safety', 'Fire & Safety Engineering Techniques'),
    ('Fire and Safety', 'Fire Engineering & Safety Management'),
    ('Fire and Safety', 'Occupational Safety, Health & Environmental Mgmt'),
    ('Fire and Safety', 'Environment Safety Engineering'),
    ('Fire and Safety', 'Fire Man Technician'),
    ('Fire and Safety', 'Health, Environment & Safety Engineering'),
    ('Fire and Safety', 'Construction Safety Management'),
    ('Fire and Safety', 'Health, Safety & Environment Management'),
    ('Fire and Safety', 'Fire & Construction Safety Management'),
    ('Fire and Safety', 'Industrial Safety Engineering'),
    ('Fire and Safety', 'Industrial Safety & Disaster Management'),
    ('Fire and Safety', 'Fire And Construction Safety Management'),
    ('Fire and Safety', 'Fire & Industrial Safety Management'),
    ('Fire and Safety', 'Sub Fire Station Officer'),
    ('Fire and Safety', 'Occupational Safety & Health'),
    ('Fire and Safety', 'Chemical Plant Processing Safety & Management'),
    ('Fire and Safety', 'Petro Chemical Process Safety & Engineering'),
    ('Fire and Safety', 'Industrial Environmental Safety'),
    ('Fire and Safety', 'Hazard Analysis Critical Control Point'),
    ('Fire and Safety', 'Power Plant Engineering, Safety & Technology'),
    ('Fire and Safety', 'Occupational Health, Safety, Environment & Risk Mgmt'),
    ('Fire and Safety', 'Fire Engineering'),
    ('Fire and Safety', 'Offshore, Rig, Oil And Gas Safety Engineering'),
    ('Fire and Safety', 'Oil And Gas Safety Engineering'),
    ('Fire and Safety', 'Occupational Safety, Health & Environment Mgmt'),
    ('Fire and Safety', 'Transport Of Hazardous And Dangerous Goods By Road'),
    ('Fire and Safety', 'Fire & Safety Engineering'),
    ('Fire and Safety', 'Fire Safety & Security Management'),
    ('Fire and Safety', 'Fire, Industrial & Environment Health Safety Mgmt'),
    ('Fire and Safety', 'Fire Engineering& Industrial Safety Management'),
    ('Fire and Safety', 'Health Safety & Environment Engineer'),
    ('Fire and Safety', 'Oil & Gas Safety Management'),
    ('Fire and Safety', 'Fire & Safety'),
    ('Forest and Environmental', 'Agro – Forest Education'),
    ('Forest and Environmental', 'Rural Management'),
    ('Forest and Environmental', 'Pollution Control Management'),
    ('Forest and Environmental', 'Sustainable Environmental Management'),
    ('Forest and Environmental', 'Soil Conservation & Rural Construction Technology'),
    ('Forest and Environmental', 'Environmental Administration'),
    ('Forest and Environmental', 'Agro-forest Products Storage Technician'),
    ('Forest and Environmental', 'Agro-forest Products Packing Technician'),
    ('Forest and Environmental', 'Agro-forest Products Quality Control Technician'),
    ('Forest and Environmental', 'Agro-forest Processing Technician'),
    ('Forest and Environmental', 'Erosion Technology'),
    ('Gems and Jewellery', 'Jewel Manufacturing'),
    ('Gems and Jewellery', 'Jewel Casting Techniques'),
    ('Gems and Jewellery', 'Gold Refining & Assaying Techniques'),
    ('Gems and Jewellery', 'Electroplating & Polishing'),
    ('Gems and Jewellery', 'Jewellery Professional Course'),
    ('Gems and Jewellery', 'Jewel Designing Cad'),
    ('Gems and Jewellery', 'Gemmology'),
    ('Gems and Jewellery', 'Stone Setting (metal Setting)'),
    ('Gems and Jewellery', 'Jewellery Appraiser'),
    ('Gems and Jewellery', 'Jewellery Sales Man/woman'),
    ('Gems and Jewellery', 'Diamond Grading'),
    ('Gems and Jewellery', 'Jewellery Hostess'),
    ('Gems and Jewellery', 'Jewels & Precious Metal Technician'),
    ('Geo Information Systems', 'Geographic Information System'),
    ('Geo Information Systems', 'GPS Navigation System'),
    ('Geo Information Systems', 'Geo-satelitte Communication'),
    ('Geo Information Systems', 'GPS Instrument Technology'),
    ('Geo Information Systems', 'Remote Sensing And GIS Technology'),
    ('Hotel Management and Tourism', 'Hotel Management & Tourism'),
    ('Hotel Management and Tourism', 'Hotel Management & Catering Science'),
    ('Hotel Management and Tourism', 'Hotel Management'),
    ('Hotel Management and Tourism', 'Institutional House Keeping'),
    ('Hotel Management and Tourism', 'Hotel Operation & Management'),
    ('Hotel Management and Tourism', 'Tourism Administration'),
    ('Hotel Management and Tourism', 'Bakery Baking Technician'),
    ('Hotel Management and Tourism', 'Travel Counselors'),
    ('Hotel Management and Tourism', 'Preparation Of Tomato Ketchup/pickles'),
    ('Hotel Management and Tourism', 'Food Production'),
    ('Hotel Management and Tourism', 'Food And Beverage Service'),
    ('Hotel Management and Tourism', 'Bakery And Confectionery'),
    ('Hotel Management and Tourism', 'Front Office Management'),
    ('Hotel Management and Tourism', 'Canning And Preservation'),
    ('Hotel Management and Tourism', 'Tourist Guide'),
    ('Hotel Management and Tourism', 'Snacks Preservation'),
    ('Hotel Management and Tourism', 'Counter Sale/reservation Assistant'),
    ('Hotel Management and Tourism', 'Vinegar Making'),
    ('Hotel Management and Tourism', 'Bell Caption'),
    ('Hotel Management and Tourism', 'Small Hotel & Motel Operating Techniques'),
    ('Hotel Management and Tourism', 'Vegetable Carving'),
    ('Hotel Management and Tourism', 'Fish Food Processing'),
    ('Hotel Management and Tourism', 'Fruit Processing (jam, Jelly, Juice)'),
    ('Hotel Management and Tourism', 'Attendants In Star Hotel, Flight And Railway Catering'),
    ('Hotel Management and Tourism', 'General Receptionist'),
    ('Hotel Management and Tourism', 'Tourism And Travel Technician'),
    ('Hotel Management and Tourism', 'Corporate House Keeping'),
    ('Hotel Management and Tourism', 'Professional Cookery'),
    ('Hotel Management and Tourism', 'Catering Sciences'),
    ('Hotel Management and Tourism', 'Snacks Production'),
    ('Hotel Management and Tourism', 'Food Preservation'),
    ('Hotel Management and Tourism', 'Hospitality Management'),
    ('Hotel Management and Tourism', 'Food Technology Course'),
    ('Hotel Management and Tourism', 'House Keeping'),
    ('Hotel Management and Tourism', 'Culinary Skills'),
    ('Hotel Management and Tourism', 'Catering Technology'),
    ('Hotel Management and Tourism', 'Food And Nutrition'),
    ('Hotel Management and Tourism', 'Food Processing And Preservation'),
    ('Hotel Management and Tourism', 'Tourism And Travel Agency Management'),
    ('Hotel Management and Tourism', 'Craftsmanship In Bartending'),
    ('Hotel Management and Tourism', 'Advanced Mixology'),
    ('Hotel Management and Tourism', 'Mixology & Bartending'),
    ('Language Studies', 'English'),
    ('Language Studies', 'German'),
    ('Language Studies', 'French'),
    ('Language Studies', 'Hindi'),
    ('Language Studies', 'Urdu Education'),
    ('Language Studies', 'Teaching English To Speaker Of Other Languages'),
    ('Language Studies', 'Tamil Vazhi Samaskirutham'),
    ('Language Studies', 'South Indian Temple Traditions In Tamil And Sanskrit'),
    ('Creative Industry', 'Vocal Music'),
    ('Creative Industry', 'Cine Music Direction'),
    ('Creative Industry', 'Electronic Media'),
    ('Creative Industry', 'Tampura Player'),
    ('Creative Industry', 'Flute Player'),
    ('Creative Industry', 'Key Board'),
    ('Creative Industry', 'Veena'),
    ('Creative Industry', 'Violin'),
    ('Creative Industry', 'Bharatanatyam'),
    ('Siddha Medicine', 'Traditional Siddha'),
    ('Siddha Medicine', 'Siddha & Ayurveda'),
    ('Siddha Medicine', 'Herbal Medicines'),
    ('Siddha Medicine', 'Siddha Food Production'),
    ('Siddha Medicine', 'Skin Care In Siddha'),
    ('Siddha Medicine', 'Hair Fall Management By Herbals'),
    ('Siddha Medicine', 'Infertility Treating By Herbology'),
    ('Siddha Medicine', 'Siddha Patient Care Assistant'),
    ('Siddha Medicine', 'Traditional Health Science'),
    ('Siddha Medicine', 'Electro Magnetism & Herbal Remedies'),
    ('Siddha Medicine', 'Herbal Siddha Medicine'),
    ('Siddha Medicine', 'Bio Electro Magnetism & Herbal Remedies'),
    ('Siddha Medicine', 'Varma Kalai And Thokkanam'),
    ('Siddha Medicine', 'Nutrition And Herbal Remedies'),
    ('Siddha Medicine', 'Clinical Siddha Practices'),
    ('Siddha Medicine', 'Traditonal Health Practices'),
    ('Siddha Medicine', 'Siddha Science'),
    ('Siddha Medicine', 'Varma Practices'),
    ('Siddha Medicine', 'Traditional Health Practices'),
    ('Siddha Medicine', 'Siddha Dietotherapy'),
    ('Sports', 'Adventure Sports For Trainers'),
    ('Sports', 'Sports Management'),
    ('Sports', 'Adventure Sports'),
    ('Sports', 'Physical Education'),
    ('Sports', 'Sports Instruments Technology'),
    ('Sports', 'Sports Instrument Technician'),
    ('Sports', 'Martial Art Trainer'),
    ('Sports', 'Acrobatic Rock & Roll'),
    ('Technical Training', 'Cnc Machine Operation (Turning & Milling)'),
    ('Technical Training', 'General Machinist'),
    ('Technical Training', 'Advance Instrument Technology'),
    ('Technical Training', 'Call Center Technician'),
    ('Technical Training', 'Jewels & Precious Metal Technology'),
    ('Technical Training', 'Jigs & Fixture Maker'),
    ('Technical Training', 'Lens & Prism Grinding Technology'),
    ('Technical Training', 'Pipe And Pressure Vessels Technology'),
    ('Technical Training', 'Structural Welding Technology'),
    ('Technical Training', 'Welding Technology'),
    ('Technical Training', 'Tig And Mig Welding Technology'),
    ('Technical Training', 'Industrial Automation'),
    ('Technical Training', 'Carpentry'),
    ('Technical Training', 'Industrial Instrument Technician'),
    ('Technical Training', 'Instrument Technician'),
    ('Technical Training', 'Mechanical Fitter'),
    ('Technical Training', 'Plumbing'),
    ('Technical Training', 'Chemical Lab Technology'),
    ('Technical Training', 'Oil Mills Processing Technician'),
    ('Technical Training', 'Food Grain Mill Processing Technician'),
    ('Technical Training', 'Tie & Dye Technician'),
    ('Technical Training', 'Embeded Systems & PLC Technology'),
    ('Technical Training', 'Advanced Diesel Technology'),
    ('Technical Training', 'X Ray Welding'),
    ('Technical Training', 'Printing Technology'),
    ('Technical Training', 'Instructor Training'),
    ('Technical Training', 'Hollow Block Making'),
    ('Technical Training', 'Electrical Wiring Technician'),
    ('Technical Training', 'Screen Printing'),
    ('Technical Training', 'Textile Mechatronics'),
    ('Technical Training', 'Auto Mechanic'),
    ('Technical Training', 'Mechanical Engineering Techniques'),
    ('Technical Training', 'Gas & Arc Welder'),
    ('Technical Training', 'Tool & Die Making'),
    ('Technical Training', 'Electrical In Wiring & Electronics'),
    ('Technical Training', 'Process Control And Instrumentation'),
    ('Technical Training', 'Massonery'),
    ('Technical Training', 'Oil & Gas Safety Management'),
    ('Technical Training', 'Diesel Mechanism (stationery & Mobile Engines)'),
    ('Technical Training', 'Attendant Operator Of Chemical Plant'),
    ('Technical Training', 'Fiber Optic Technician'),
    ('Technical Training', 'Earth Moving Equipment Repairing'),
    ('Technical Training', 'Dealers Service Mechanic'),
    ('Technical Training', 'Production Technology'),
    ('Technical Training', 'Production Techniques'),
    ('Technical Training', 'Elevator Technology'),
    ('Technical Training', 'Leather And Footwear Technology'),
    ('Technical Training', 'Mep Engineering Facility Management'),
    ('Technical Training', 'Power Plant Operation And Maintenance Engineering'),
    ('Technical Training', 'Turner'),
    ('Technical Training', 'Material Testing & Machine Operator'),
    ('Technical Training', 'Mechanic Auto Body Painting'),
    ('Technical Training', 'Mechanic Auto Body Repair'),
    ('Technical Training', 'Mep Operation And Maintenance Engineering'),
    ('Textile Technology', 'Textile Technology'),
    ('Textile Technology', 'Printing On Clothes'),
    ('Textile Technology', 'Textile Machinery Technology'),
    ('Textile Technology', 'Textile Lab Technician'),
    ('Textile Technology', 'Textile Lab Technology'),
    ('Textile Technology', 'Yarn Making'),
    ('Unani Medicine', 'Unani & Acupuncture'),
    ('Unani Medicine', 'Unani For Chronic Ailments'),
    ('Unani Medicine', 'Unani For Kidney Diseases'),
    ('Unani Medicine', 'Basic Unani'),
    ('Unani Medicine', 'Advance Unani'),
    ('Unani Medicine', 'Unani Pharmacy'),
    ('Unani Medicine', 'Hijama Therapy'),
    ('Unani Medicine', 'Unani Science'),
    ('Yoga and Naturopathy', 'Yoga & Naturopathy'),
    ('Yoga and Naturopathy', 'Naturopathy & Yogic Science'),
    ('Yoga and Naturopathy', 'Yoga & Massage'),
    ('Yoga and Naturopathy', 'Varma And Yoga'),
    ('Yoga and Naturopathy', 'Naturopathy'),
    ('Yoga and Naturopathy', 'Herbal Drug Manufacturing'),
    ('Yoga and Naturopathy', 'Practical Yoga'),
    ('Yoga and Naturopathy', 'Nature Cure'),
    ('Yoga and Naturopathy', 'Yogic Science'),
    ('Yoga and Naturopathy', 'Pranic Healing And Yoga'),
    ('Yoga and Naturopathy', 'Water Therapy And Natural Diet'),
    ('Yoga and Naturopathy', 'Reiki Therapy And Nature Science'),
    ('Yoga and Naturopathy', 'Arthritic Care & Natural Diet'),
    ('Yoga and Naturopathy', 'Pulse Diagnosing In Natural Science'),
    ('Yoga and Naturopathy', 'Color Therapy And Nature Cure'),
    ('Yoga and Naturopathy', 'Gem Therapy And Yoga'),
    ('Yoga and Naturopathy', 'Chakras And Natural Science'),
    ('Yoga and Naturopathy', 'Hypnotherapy And Yoga'),
    ('Yoga and Naturopathy', 'Herbal Nutrition Basics And Yoga'),
    ('Yoga and Naturopathy', 'Natural Vitamins & Minerals'),
    ('Yoga and Naturopathy', 'Metabolism & Nutrition By Natural Diet'),
    ('Yoga and Naturopathy', 'Energy Therapy And Yoga'),
    ('Yoga and Naturopathy', 'Herbs & Natural Diet'),
    ('Yoga and Naturopathy', 'Spinal Manipulation By Naturopathy'),
    ('Yoga and Naturopathy', 'Child Health By Yoga'),
    ('Yoga and Naturopathy', 'Breathing Techniques By Yoga'),
    ('Yoga and Naturopathy', 'Cemind Memory Personality Development By Yoga'),
    ('Yoga and Naturopathy', 'Science Of Happy And Healthy Living By Natural Diet'),
    ('Yoga and Naturopathy', 'Pyramid Therapy And Yoga'),
    ('Yoga and Naturopathy', 'Vastu Shastra And Nature Science'),
    ('Yoga and Naturopathy', 'Fasting And Naturopathy'),
    ('Yoga and Naturopathy', 'Hydro Therapy And Yoga'),
    ('Yoga and Naturopathy', 'Pillars Of Health And Natural Science'),
    ('Yoga and Naturopathy', 'Therapeutic Yoga'),
    ('Yoga and Naturopathy', 'Naturopathy Food'),
    ('Yoga and Naturopathy', 'Yoga'),
    ('Yoga and Naturopathy', 'Body Building (health), Fitness & Nutrition'),
    ('Yoga and Naturopathy', 'Yoga & Naturopathic Science'),
    ('Yoga and Naturopathy', 'Yoga & Acupuncture'),
    ('Yoga and Naturopathy', 'Yoga & Nature Cure'),
    ('Yoga and Naturopathy', 'Holistic Therapy'),
    ('Yoga and Naturopathy', 'Integrative Alternative Therapies'),
    ('Yoga and Naturopathy', 'Yoga & Naturopathy Science'),
    ('Yoga and Naturopathy', 'Yoga Teacher Education'),
    ('Yoga and Naturopathy', 'Drug Store Management'),
    ('Yoga and Naturopathy', 'Ozone Therapy'),
    ('Yoga and Naturopathy', 'Hypnotherapy'),
    ('Yoga and Naturopathy', 'Quantum Magnetic Health Analyser & Health Advisor'),
    ('Yoga and Naturopathy', 'Intutive Mind Empowerment Course'),
    ('Yoga and Naturopathy', 'Magnetic Bio Health Analyzer'),
    ('Yoga and Naturopathy', 'Bio-plasmic Modulation Therapy'),
    ('Yoga and Naturopathy', 'Cupping Therapy'),
    ('Yoga and Naturopathy', 'Meditation, Yoga And Tantra'),
    ('Yoga and Naturopathy', 'Hypnosis'),
    ('Yoga and Naturopathy', 'Past Life Regression'),
    ('Yoga and Naturopathy', 'Bindu Chikitsa And Naturopathy Science'),
    ('Yoga and Naturopathy', 'Mudra Teacher Course'),
    ('Management', 'Human Resours Management'),
    ('Management', 'Retail Mangement'),
    ('Management', 'Hospital Documentation And Record Management'),
    ('Management', 'Village Health Worker'),
    ('Management', 'Hospital Management'),
    ('Management', 'Multi Purpose Health Worker'),
    ('Management', 'Awareness Of Hiv & Aids'),
    ('Management', 'Hospital House Keeping'),
    ('Management', 'Hospital Waste Management'),
    ('Management', 'Old Age Care'),
    ('Management', 'Female Patient Care Assistant'),
    ('Management', 'Patient Care Administration'),
    ('Management', 'Hospital Front Office Management'),
    ('Management', 'Hospital Administration'),
    ('Management', 'Health Care Assistant'),
    ('Management', 'Nanny Care'),
    ('Management', 'First Aid'),
    ('Management', 'Diet And Nutrition'),
    ('Management', 'Optical Fitter Assistant'),
    ('Management', 'Hospital Dietary Service Assistant'),
    ('Management', 'Geriatric Care Taker Assistant'),
    ('Management', 'Diet & Nutrition'),
    ('Management', 'Medical Transcription'),
    ('Management', 'Medical Equipment Technician'),
    ('Management', 'Health Care Management'),
    ('Management', 'Dietician'),
    ('Management', 'Dental Hygienist'),
    ('Management', 'Medical Transcript Technician'),
    ('Management', 'Medical Record Sciences'),
    ('Aviation', 'International Airline & Travel Management'),
    ('Aviation', 'Airport Management'),
    ('Aviation', 'Cabin Crew Management'),
    ('Aviation', 'Air Cargo Practices & Documentation'),
    ('Aviation', 'Domestic Airline & Travel Management'),
    ('Aviation', 'Airline Travel & Tourism And Hospitality Management'),
    ('Aviation', 'Air Hostess Training'),
    ('Aviation', 'Airport Ground Staff Training'),
    ('Aviation', 'Air Fares & Ticketing'),
    ('Aviation', 'Air Fare & Ticketing Management'),
    ('Aviation', 'Aviation Safety'),
    ('Aviation', 'Airline Management'),
    ('Aviation', 'Air Cargo & Hotel Management'),
    ('Aviation', 'Airport & Hotel Management'),
    ('Aviation', 'Aviation & Hotel Management'),
    ('Aviation', 'Air/sea Cargo Management'),
    ('Aviation', 'Aviation And Hospitality Management'),
    ('Banking and Finance', 'Banking'),
    ('Banking and Finance', 'Investment Banking'),
    ('Banking and Finance', 'Treasury And Forex Management'),
    ('Banking and Finance', 'Insurance'),
    ('Banking and Finance', 'Accounting'),
    ('Banking and Finance', 'Accounting Standards And Us Gaap'),
    ('Banking and Finance', 'Forensic Accounting'),
    ('Banking and Finance', 'Information Systems Audit'),
    ('Banking and Finance', 'Business Finance'),
    ('Banking and Finance', 'Financial Engineering'),
    ('Banking and Finance', 'Strategic Finance And Control'),
    ('Banking and Finance', 'Investment And Tax Planning'),
    ('Banking and Finance', 'Cyber Law'),
    ('Banking and Finance', 'Intellectual Property Rights'),
    ('Banking and Finance', 'Environmental Law'),
    ('Banking and Finance', 'Alternative Dispute Resolution'),
    ('Banking and Finance', 'International Business Law'),
    ('Banking and Finance', 'Securities Law'),
    ('Banking and Finance', 'Banking Laws & Loan Management'),
    ('Banking and Finance', 'Hospital Laws & Management'),
    ('Banking and Finance', 'Project Management'),
    ('Banking and Finance', 'Export And Import Management'),
    ('Banking and Finance', 'Management Of E-business'),
    ('Banking and Finance', 'Global Strategic Management'),
    ('Banking and Finance', 'Enterprise Risk Management'),
    ('Banking and Finance', 'Marketing Management'),
    ('Banking and Finance', 'Customer Relationship Management'),
    ('Banking and Finance', 'Marketing Financial Products'),
    ('Banking and Finance', 'Brand Management'),
    ('Banking and Finance', 'Marketing Communications'),
    ('Banking and Finance', 'Industrial Marketing'),
    ('Banking and Finance', 'Leadership And Change Management'),
    ('Banking and Finance', 'Training And Development'),
    ('Banking and Finance', 'Performance Management'),
    ('Banking and Finance', 'Supply Chain Management'),
    ('Banking and Finance', 'Quality Management'),
    ('Banking and Finance', 'Financial Accounting'),
    ('Banking and Finance', 'Financial Statement Analysis'),
    ('Banking and Finance', 'Management Accounting'),
    ('Banking and Finance', 'Auditing'),
    ('Banking and Finance', 'Financial Markets'),
    ('Banking and Finance', 'International Finance'),
    ('Banking and Finance', 'Mergers And Acquisitions'),
    ('Banking and Finance', 'Financial Institutions'),
    ('Banking and Finance', 'Financial Management'),
    ('Banking and Finance', 'Financial Services'),
    ('Banking and Finance', 'Financial Risk Management'),
    ('Banking and Finance', 'Equity Valuation'),
    ('Banking and Finance', 'Derivative Valuation'),
    ('Banking and Finance', 'Debt Valuation'),
    ('Banking and Finance', 'Security Analysis'),
    ('Banking and Finance', 'Mutual Funds'),
    ('Banking and Finance', 'Portfolio Management'),
    ('Banking and Finance', 'Financial Planning'),
    ('Banking and Finance', 'Money & Banking'),
    ('Banking and Finance', 'Commercial Banking'),
    ('Banking and Finance', 'International Banking'),
    ('Banking and Finance', 'Banking Operations'),
    ('Banking and Finance', 'Central Banking'),
    ('Banking and Finance', 'Credit Management'),
    ('Banking and Finance', 'Bank Marketing'),
    ('Banking and Finance', 'Life Insurance'),
    ('Banking and Finance', 'Health Insurance'),
    ('Banking and Finance', 'Insurance Underwriting'),
    ('Banking and Finance', 'Insurance Operations'),
    ('Banking and Finance', 'Actuarial Principles & Practices'),
    ('Banking and Finance', 'General Insurance'),
    ('Banking and Finance', 'Insurance Marketing'),
    ('Banking and Finance', 'Claims Management'),
    ('Banking and Finance', 'Insurance Investments'),
    ('Banking and Finance', 'Reinsurance'),
    ('Banking and Finance', 'Business Law'),
    ('Banking and Finance', 'Indirect Taxation'),
    ('Banking and Finance', 'Direct Taxation'),
    ('Banking and Finance', 'Business Strategy'),
    ('Banking and Finance', 'Business Research Methods'),
    ('Banking and Finance', 'Operations Management'),
    ('Banking and Finance', 'Management Control Systems'),
    ('Banking and Finance', 'Business Economics'),
    ('Banking and Finance', 'Business Communication'),
    ('Banking and Finance', 'IT In Management'),
    ('Banking and Finance', 'Business Ethics'),
    ('Banking and Finance', 'Sales & Distribution Management'),
    ('Banking and Finance', 'Consumer Behavior'),
    ('Banking and Finance', 'Global Business Environment'),
    ('Banking and Finance', 'Multinational Corporations'),
    ('Banking and Finance', 'International Business'),
    ('Banking and Finance', 'Organizational Behavior'),
    ('Banking and Finance', 'Managerial Effectiveness'),
    ('Banking and Finance', 'Ngo Management'),
    ('Banking and Finance', 'Library And Information Sciences'),
    ('Banking and Finance', 'Event Management Technician'),
    ('Banking and Finance', 'Insurance Agent'),
    ('Banking and Finance', 'Foreign Trade'),
    ('Banking and Finance', 'Material Management'),
    ('Banking and Finance', 'Personnel Management & Industrial Relations'),
    ('Banking and Finance', 'Production & Operation Management'),
    ('Banking and Finance', 'Production Management Control'),
    ('Banking and Finance', 'Human Resource Management'),
    ('Banking and Finance', 'Community Development'),
    ('Banking and Finance', 'Welfare Law'),
    ('Banking and Finance', 'International Shipping Mgmt & Export,import Mgmt'),
    ('Banking and Finance', 'Retail Management'),
    ('Banking and Finance', 'Exim And Logistics Supply Chain Management'),
    ('Fashion Design', 'Fashion Technology'),
    ('Fashion Design', 'Computerised Fashion Designing'),
    ('Fashion Design', 'Cushion And Pillow Making'),
    ('Fashion Design', 'Applique Work'),
    ('Fashion Design', 'Quilt Work'),
    ('Fashion Design', 'Machine Embroidery'),
    ('Fashion Design', 'Hand Embroidery'),
    ('Fashion Design', 'Wool Knitting'),
    ('Fashion Design', 'Lace Making'),
    ('Fashion Design', 'Decorative Stitches'),
    ('Fashion Design', 'Crochet Work'),
    ('Fashion Design', 'Batik Printing'),
    ('Fashion Design', 'Fabric Painting'),
    ('Fashion Design', 'Rubber Painting'),
    ('Fashion Design', 'Saree Designing'),
    ('Fashion Design', 'Smoking Works'),
    ('Fashion Design', 'Electric Embroidery Machine Operator'),
    ('Fashion Design', 'Tailor'),
    ('Fashion Design', 'Dress Making Techniques'),
    ('Fashion Design', 'Hair Dressing Technician'),
    ('Fashion Design', 'Tailoring Trainer'),
    ('Fashion Design', 'Fashion Designing Assistant'),
    ('Fashion Design', 'Hair Dressing Techniques'),
    ('Fashion Design', 'Tailoring'),
    ('Fashion Design', 'Apparel Manufacturing&advance Pattern Making Technology'),
    ('Media and Film', 'Digital Photography'),
    ('Media and Film', 'Visual Media'),
    ('Media and Film', 'Digital Videography'),
    ('Media and Film', 'Digital Cinematography'),
    ('Media and Film', 'Film Editing – Non Linear Editing'),
    ('Media and Film', 'Dark Room Technician'),
    ('Media and Film', 'Sound Engineering'),
    ('Media and Film', 'Direction & Screen Play Writing'),
    ('Media and Film', 'Audio – Visual Effects Technician'),
    ('Media and Film', 'Cinema Acting'),
    ('Media and Film', 'Screen Play Writing'),
    ('Media and Film', 'Journalism & Mass Communication'),
    ('Media and Film', 'Computer Dubbing-recording'),
    ('Media and Film', 'Visual Communication'),
    ('Media and Film', 'Cinematography'),
    ('Media and Film', 'Radio Jockey'),
    ('Media and Film', 'Direction'),
    ('Media and Film', 'Direction & Script Writing'),
    ('Media and Film', 'Recording Arts & Music Technology'),
    ('Media and Film', 'Editing,vfx & Digital Intermediate'),
    ('Media and Film', 'Advertising & Media Communication'),
    ('Media and Film', 'Radio,video Jockey & News Reading'),
    ('Media and Film', 'Editing,vfx'),
    ('Media and Film', 'Direction And Screenplay Writing'),
    ('Media and Film', 'Advertising'),
    ('Logistics and Transportation', 'Logistics'),
    ('Logistics and Transportation', 'Logistics & Supply Chain Management'),
    ('Logistics and Transportation', 'Logistics & Warehouse Management'),
    ('Logistics and Transportation', 'Domestic Shipping Management'),
    ('Logistics and Transportation', 'International Shipping Management'),
    ('Logistics and Transportation', 'Transportation And Fleet'),
    ('Logistics and Transportation', 'Inventorymanagement'),
    ('Logistics and Transportation', 'E-commerce Logistics'),
    ('Logistics and Transportation', 'Cold Chain Logistics'),
    ('Logistics and Transportation', 'Customs And Import-export'),
    ('Marine Technology', 'Crew Management'),
    ('Marine Technology', 'Ship Safety Management'),
    ('Marine Technology', 'Ship Catering Management'),
    ('Marine Technology', 'Port Operations & Management'),
    ('Marine Technology', 'Cabin Room Technician'),
    ('Marine Technology', 'Marine Diesel Engineering'),
    ('Marine Technology', 'Marine Diesel Engine Mechanic'),
    ('Marine Technology', 'Certification Ansys Aqwa'),
    ('Marine Technology', 'Ansys Fluent'),
    ('Marine Technology', 'Cfd'),
    ('Marine Technology', 'Computer Application In Design Of Offshore Structure'),
    ('Marine Technology', 'Computer Application In Hull Form Design'),
    ('Marine Technology', 'Computer Application In Seakeeping And Maneuvering'),
    ('Marine Technology', 'Computer Application In Structural Analysis Of Ships'),
    ('Marine Technology', 'Design Of Special Purpose Vessel'),
    ('Marine Technology', 'Engineering Economics In Ship Design'),
    ('Marine Technology', 'Maxsurf, Moses, Sacs'),
    ('Marine Technology', 'Ship Design'),
    ('Marine Technology', 'Ship Resistance And Propulsion'),
    ('Marine Technology', 'Ship Stability'),
    ('Marine Technology', 'Computer Application In Ship Design'),
    ('Marine Technology', 'Oil Rig And Drilling Process'),
    ('Marine Technology', 'Ship Building And Offshore Technology'),
    ('Marine Technology', 'Ship Draughtsman'),
    ('Marine Technology', 'Subsea & Pipeline Engineering'),
    ('Marine Technology', 'Cruise Line Management'),
    ('Solar Technology', 'Solar Technology'),
    ('Solar Technology', 'Solar Energy System Design Course'),
    ('Solar Technology', 'Training On Installation And Maintenance Of Solar Power Plan'),
    ('Solar Technology', 'Solar Engineering Techniques'),
    ('Solar Technology', 'Entrepreneurship In The Field Of Renewable Energy'),
    ('Solar Technology', 'Renewal Energy And Its Application In The Field Of Solar'),
    ('Solar Technology', 'Solar Photovoltaic Engineering Assistant'),
    ('Solar Technology', 'Senior Solar Photovoltaic Technician'),
    ('Solar Technology', 'Junior Solar Photovoltaic Technician'),
    ('Solar Technology', 'Senior Solar Photovoltaic Panel Assembling Technician'),
    ('Solar Technology', 'Senior Solar Pcu Technician'),
    ('Solar Technology', 'Solar System & Inverter Installation And Servicing'),
    ('Solar Technology', 'Solar Plant & Electrical Technology'),
    ('Solar Technology', 'Solar Pv Technical Sales'),
    ('Solar Technology', 'Solar Pv Design And Installation'),
    ('Solar Technology', 'Design Of Solar Utility Power'),
    ('Solar Technology', 'Pv Design Using Pvsyst, Pvsol And Sam'),
    ('Mental Health', 'Psycho Therapy'),
    ('Mental Health', 'Guidance And Counselling'),
    ('Mental Health', 'Learning Disability'),
    ('Mental Health', 'Learning Disorder'),
    ('Mental Health', 'Early Childhood Special Education'),
    ('Mental Health', 'Psychological Guidance & Counseling'),
    ('Mental Health', 'Autism Spectrum Disorder Education'),
    ('Mental Health', 'Mind Tuning Art'),
    ('Mental Health', 'Therapeutic Hipnosis'),
    ('Mental Health', 'Cognitive Behaviour Therapy'),
    ('Mental Health', 'Counseling Psychology'),
    ('Marketing', 'Door To Door'),
    ('Marketing', 'Digital Marketing'),
    ('Marketing', 'Product Sales Marketing'),
    ('Marketing', 'Brand Management'),
    ('Marketing', 'Automation'),
    ('Marketing', 'Tele Marketing'),
    ('Marketing', 'Consumer Behaviour'),
    ('Marketing', 'Marketing Analytics'),
    ('Marketing', 'Services Marketing'),
    ('Marketing', 'Strategic Marketing'),
    ('Marketing', 'Marketing Communications')
), levels(prefix, duration, fees, suffix) as (
  values
    ('Certificate in ', '6 Months', 6000::numeric, 'cert'),
    ('Diploma in ', '11 Months', 10000::numeric, 'dip')
), mode_ref as (
  select id from education_modes where name = 'Skill Certification'
), expanded as (
  select
    bc.sector_name,
    bc.topic,
    l.prefix || bc.topic as course_name,
    l.duration,
    l.fees,
    lower(
      regexp_replace(
        regexp_replace(
          regexp_replace(
            bc.sector_name || '-' || bc.topic || '-' || l.suffix || '-skill',
            '&', ' and ', 'gi'
          ),
          '[^a-zA-Z0-9]+', '-', 'g'
        ),
        '(^-+)|(-+$)', '', 'g'
      )
    ) as slug
  from base_courses bc
  cross join levels l
)
insert into courses(name, slug, sector_id, mode_id, duration, description)
select
  e.course_name,
  e.slug,
  s.id,
  m.id,
  e.duration,
  'Skill certification program in ' || e.sector_name || ': ' || e.topic
from expanded e
join course_sectors s on s.name = e.sector_name
cross join mode_ref m
on conflict (slug) do nothing;

with g as (
  select id from universities where slug = 'glocal-university'
), cs as (
  select
    c.id,
    c.duration,
    case
      when c.slug like '%-cert-skill' then 6000::numeric
      when c.slug like '%-dip-skill' then 10000::numeric
      else 6000::numeric
    end as fees
  from courses c
  join education_modes m on m.id = c.mode_id
  where m.name = 'Skill Certification'
    and (c.slug like '%-cert-skill' or c.slug like '%-dip-skill')
)
insert into university_courses(university_id, course_id, fees, duration)
select g.id, cs.id, cs.fees, cs.duration
from g cross join cs
on conflict (university_id, course_id) do nothing;

insert into students(course_id, university_id, student_count)
select
  uc.course_id,
  uc.university_id,
  100 + (abs(('x' || substr(md5(uc.course_id::text || uc.university_id::text || 'skill-full'), 1, 8))::bit(32)::int) % 1401)
from university_courses uc
join universities u on u.id = uc.university_id and u.slug = 'glocal-university'
join courses c on c.id = uc.course_id
where c.slug like '%-cert-skill' or c.slug like '%-dip-skill'
on conflict (course_id, university_id) do update
set student_count = excluded.student_count;

insert into ratings(course_id, rating, review_count)
select
  c.id,
  round((3.8 + ((abs(('x' || substr(md5(c.slug || '-skill-rate-full'), 1, 8))::bit(32)::int) % 10) / 10.0))::numeric, 1),
  25 + (abs(('x' || substr(md5(c.slug || '-skill-reviews-full'), 1, 8))::bit(32)::int) % 326)
from courses c
where c.slug like '%-cert-skill' or c.slug like '%-dip-skill'
on conflict (course_id) do update
set rating = excluded.rating,
    review_count = excluded.review_count;

-- verification
-- select count(*) from courses c join education_modes m on m.id = c.mode_id where m.name='Skill Certification';
